// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Simaky/go-github-tracker/backend/ent/repo"
)

// RepoCreate is the builder for creating a Repo entity.
type RepoCreate struct {
	config
	mutation *RepoMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepoCreate) SetCreatedAt(v time.Time) *RepoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepoCreate) SetNillableCreatedAt(v *time.Time) *RepoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RepoCreate) SetUpdatedAt(v time.Time) *RepoCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RepoCreate) SetNillableUpdatedAt(v *time.Time) *RepoCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwner sets the "owner" field.
func (_c *RepoCreate) SetOwner(v string) *RepoCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RepoCreate) SetName(v string) *RepoCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *RepoCreate) SetFullName(v string) *RepoCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RepoCreate) SetDescription(v string) *RepoCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RepoCreate) SetNillableDescription(v *string) *RepoCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStars sets the "stars" field.
func (_c *RepoCreate) SetStars(v int) *RepoCreate {
	_c.mutation.SetStars(v)
	return _c
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_c *RepoCreate) SetNillableStars(v *int) *RepoCreate {
	if v != nil {
		_c.SetStars(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *RepoCreate) SetLanguage(v string) *RepoCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *RepoCreate) SetNillableLanguage(v *string) *RepoCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetHTMLURL sets the "html_url" field.
func (_c *RepoCreate) SetHTMLURL(v string) *RepoCreate {
	_c.mutation.SetHTMLURL(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RepoCreate) SetNotes(v string) *RepoCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RepoCreate) SetNillableNotes(v *string) *RepoCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetFetchedAt sets the "fetched_at" field.
func (_c *RepoCreate) SetFetchedAt(v time.Time) *RepoCreate {
	_c.mutation.SetFetchedAt(v)
	return _c
}

// Mutation returns the RepoMutation object of the builder.
func (_c *RepoCreate) Mutation() *RepoMutation {
	return _c.mutation
}

// Save creates the Repo in the database.
func (_c *RepoCreate) Save(ctx context.Context) (*Repo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepoCreate) SaveX(ctx context.Context) *Repo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepoCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repo.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := repo.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Stars(); !ok {
		v := repo.DefaultStars
		_c.mutation.SetStars(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := repo.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepoCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Repo.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Repo.updated_at"`)}
	}
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "Repo.owner"`)}
	}
	if v, ok := _c.mutation.Owner(); ok {
		if err := repo.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Repo.owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Repo.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := repo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repo.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "Repo.full_name"`)}
	}
	if v, ok := _c.mutation.FullName(); ok {
		if err := repo.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Repo.full_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stars(); !ok {
		return &ValidationError{Name: "stars", err: errors.New(`ent: missing required field "Repo.stars"`)}
	}
	if v, ok := _c.mutation.Stars(); ok {
		if err := repo.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "Repo.stars": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTMLURL(); !ok {
		return &ValidationError{Name: "html_url", err: errors.New(`ent: missing required field "Repo.html_url"`)}
	}
	if v, ok := _c.mutation.HTMLURL(); ok {
		if err := repo.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "Repo.html_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FetchedAt(); !ok {
		return &ValidationError{Name: "fetched_at", err: errors.New(`ent: missing required field "Repo.fetched_at"`)}
	}
	return nil
}

func (_c *RepoCreate) sqlSave(ctx context.Context) (*Repo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepoCreate) createSpec() (*Repo, *sqlgraph.CreateSpec) {
	var (
		_node = &Repo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repo.Table, sqlgraph.NewFieldSpec(repo.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(repo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(repo.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(repo.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(repo.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(repo.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Stars(); ok {
		_spec.SetField(repo.FieldStars, field.TypeInt, value)
		_node.Stars = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(repo.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.HTMLURL(); ok {
		_spec.SetField(repo.FieldHTMLURL, field.TypeString, value)
		_node.HTMLURL = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(repo.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.FetchedAt(); ok {
		_spec.SetField(repo.FieldFetchedAt, field.TypeTime, value)
		_node.FetchedAt = value
	}
	return _node, _spec
}

// RepoCreateBulk is the builder for creating many Repo entities in bulk.
type RepoCreateBulk struct {
	config
	err      error
	builders []*RepoCreate
}

// Save creates the Repo entities in the database.
func (_c *RepoCreateBulk) Save(ctx context.Context) ([]*Repo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Repo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepoCreateBulk) SaveX(ctx context.Context) []*Repo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
