// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Simaky/go-github-tracker/backend/ent/predicate"
	"github.com/Simaky/go-github-tracker/backend/ent/repo"
)

// RepoUpdate is the builder for updating Repo entities.
type RepoUpdate struct {
	config
	hooks    []Hook
	mutation *RepoMutation
}

// Where appends a list predicates to the RepoUpdate builder.
func (_u *RepoUpdate) Where(ps ...predicate.Repo) *RepoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepoUpdate) SetUpdatedAt(v time.Time) *RepoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepoUpdate) SetOwner(v string) *RepoUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableOwner(v *string) *RepoUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepoUpdate) SetName(v string) *RepoUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableName(v *string) *RepoUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepoUpdate) SetFullName(v string) *RepoUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableFullName(v *string) *RepoUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepoUpdate) SetDescription(v string) *RepoUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableDescription(v *string) *RepoUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RepoUpdate) ClearDescription() *RepoUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStars sets the "stars" field.
func (_u *RepoUpdate) SetStars(v int) *RepoUpdate {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableStars(v *int) *RepoUpdate {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *RepoUpdate) AddStars(v int) *RepoUpdate {
	_u.mutation.AddStars(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *RepoUpdate) SetLanguage(v string) *RepoUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableLanguage(v *string) *RepoUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *RepoUpdate) ClearLanguage() *RepoUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepoUpdate) SetHTMLURL(v string) *RepoUpdate {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableHTMLURL(v *string) *RepoUpdate {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepoUpdate) SetNotes(v string) *RepoUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableNotes(v *string) *RepoUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RepoUpdate) ClearNotes() *RepoUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *RepoUpdate) SetFetchedAt(v time.Time) *RepoUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *RepoUpdate) SetNillableFetchedAt(v *time.Time) *RepoUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// Mutation returns the RepoMutation object of the builder.
func (_u *RepoUpdate) Mutation() *RepoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoUpdate) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := repo.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Repo.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := repo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repo.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := repo.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Repo.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stars(); ok {
		if err := repo.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "Repo.stars": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTMLURL(); ok {
		if err := repo.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "Repo.html_url": %w`, err)}
		}
	}
	return nil
}

func (_u *RepoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repo.Table, repo.Columns, sqlgraph.NewFieldSpec(repo.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repo.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repo.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repo.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repo.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(repo.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(repo.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(repo.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(repo.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(repo.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repo.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repo.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(repo.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(repo.FieldFetchedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepoUpdateOne is the builder for updating a single Repo entity.
type RepoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepoMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepoUpdateOne) SetUpdatedAt(v time.Time) *RepoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepoUpdateOne) SetOwner(v string) *RepoUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableOwner(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepoUpdateOne) SetName(v string) *RepoUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableName(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepoUpdateOne) SetFullName(v string) *RepoUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableFullName(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepoUpdateOne) SetDescription(v string) *RepoUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableDescription(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RepoUpdateOne) ClearDescription() *RepoUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStars sets the "stars" field.
func (_u *RepoUpdateOne) SetStars(v int) *RepoUpdateOne {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableStars(v *int) *RepoUpdateOne {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *RepoUpdateOne) AddStars(v int) *RepoUpdateOne {
	_u.mutation.AddStars(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *RepoUpdateOne) SetLanguage(v string) *RepoUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableLanguage(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *RepoUpdateOne) ClearLanguage() *RepoUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepoUpdateOne) SetHTMLURL(v string) *RepoUpdateOne {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableHTMLURL(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepoUpdateOne) SetNotes(v string) *RepoUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableNotes(v *string) *RepoUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RepoUpdateOne) ClearNotes() *RepoUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *RepoUpdateOne) SetFetchedAt(v time.Time) *RepoUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *RepoUpdateOne) SetNillableFetchedAt(v *time.Time) *RepoUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// Mutation returns the RepoMutation object of the builder.
func (_u *RepoUpdateOne) Mutation() *RepoMutation {
	return _u.mutation
}

// Where appends a list predicates to the RepoUpdate builder.
func (_u *RepoUpdateOne) Where(ps ...predicate.Repo) *RepoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepoUpdateOne) Select(field string, fields ...string) *RepoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repo entity.
func (_u *RepoUpdateOne) Save(ctx context.Context) (*Repo, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoUpdateOne) SaveX(ctx context.Context) *Repo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoUpdateOne) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := repo.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Repo.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := repo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repo.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := repo.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Repo.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stars(); ok {
		if err := repo.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "Repo.stars": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTMLURL(); ok {
		if err := repo.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "Repo.html_url": %w`, err)}
		}
	}
	return nil
}

func (_u *RepoUpdateOne) sqlSave(ctx context.Context) (_node *Repo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repo.Table, repo.Columns, sqlgraph.NewFieldSpec(repo.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repo.FieldID)
		for _, f := range fields {
			if !repo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repo.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repo.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repo.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repo.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(repo.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(repo.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(repo.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(repo.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(repo.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repo.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repo.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(repo.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(repo.FieldFetchedAt, field.TypeTime, value)
	}
	_node = &Repo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
