// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Simaky/go-github-tracker/backend/ent/repo"
	"github.com/Simaky/go-github-tracker/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	repoMixin := schema.Repo{}.Mixin()
	repoMixinFields0 := repoMixin[0].Fields()
	_ = repoMixinFields0
	repoFields := schema.Repo{}.Fields()
	_ = repoFields
	// repoDescCreatedAt is the schema descriptor for created_at field.
	repoDescCreatedAt := repoMixinFields0[0].Descriptor()
	// repo.DefaultCreatedAt holds the default value on creation for the created_at field.
	repo.DefaultCreatedAt = repoDescCreatedAt.Default.(func() time.Time)
	// repoDescUpdatedAt is the schema descriptor for updated_at field.
	repoDescUpdatedAt := repoMixinFields0[1].Descriptor()
	// repo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	repo.DefaultUpdatedAt = repoDescUpdatedAt.Default.(func() time.Time)
	// repo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	repo.UpdateDefaultUpdatedAt = repoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// repoDescOwner is the schema descriptor for owner field.
	repoDescOwner := repoFields[0].Descriptor()
	// repo.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	repo.OwnerValidator = repoDescOwner.Validators[0].(func(string) error)
	// repoDescName is the schema descriptor for name field.
	repoDescName := repoFields[1].Descriptor()
	// repo.NameValidator is a validator for the "name" field. It is called by the builders before save.
	repo.NameValidator = repoDescName.Validators[0].(func(string) error)
	// repoDescFullName is the schema descriptor for full_name field.
	repoDescFullName := repoFields[2].Descriptor()
	// repo.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	repo.FullNameValidator = repoDescFullName.Validators[0].(func(string) error)
	// repoDescStars is the schema descriptor for stars field.
	repoDescStars := repoFields[4].Descriptor()
	// repo.DefaultStars holds the default value on creation for the stars field.
	repo.DefaultStars = repoDescStars.Default.(int)
	// repo.StarsValidator is a validator for the "stars" field. It is called by the builders before save.
	repo.StarsValidator = repoDescStars.Validators[0].(func(int) error)
	// repoDescHTMLURL is the schema descriptor for html_url field.
	repoDescHTMLURL := repoFields[6].Descriptor()
	// repo.HTMLURLValidator is a validator for the "html_url" field. It is called by the builders before save.
	repo.HTMLURLValidator = repoDescHTMLURL.Validators[0].(func(string) error)
	// repoDescNotes is the schema descriptor for notes field.
	repoDescNotes := repoFields[7].Descriptor()
	// repo.DefaultNotes holds the default value on creation for the notes field.
	repo.DefaultNotes = repoDescNotes.Default.(string)
	// repoDescForksCount is the schema descriptor for forks_count field.
	repoDescForksCount := repoFields[9].Descriptor()
	// repo.DefaultForksCount holds the default value on creation for the forks_count field.
	repo.DefaultForksCount = repoDescForksCount.Default.(int)
	// repo.ForksCountValidator is a validator for the "forks_count" field. It is called by the builders before save.
	repo.ForksCountValidator = repoDescForksCount.Validators[0].(func(int) error)
}
