// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ReposColumns holds the columns for the "repos" table.
	ReposColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "owner", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "full_name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "stars", Type: field.TypeInt, Default: 0},
		{Name: "language", Type: field.TypeString, Nullable: true},
		{Name: "html_url", Type: field.TypeString},
		{Name: "notes", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "fetched_at", Type: field.TypeTime},
		{Name: "forks_count", Type: field.TypeInt, Default: 0},
	}
	// ReposTable holds the schema information for the "repos" table.
	ReposTable = &schema.Table{
		Name:       "repos",
		Columns:    ReposColumns,
		PrimaryKey: []*schema.Column{ReposColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "repo_language",
				Unique:  false,
				Columns: []*schema.Column{ReposColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ReposTable,
	}
)

func init() {
}
